# Generated by Django 5.2.9 on 2025-12-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50)),
                ('name', models.CharField(help_text='Residence name (e.g., Mr. & Mrs. Mensah)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'residences',
                'ordering': ['house_number'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, help_text='e.g., Home, Mobile, Work', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='residences.residence')),
            ],
            options={
                'db_table': 'residence_phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(blank=True, help_text='e.g., Personal, Work', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='residences.residence')),
            ],
            options={
                'verbose_name_plural': 'Email addresses',
                'db_table': 'residence_email_addresses',
            },
        ),
    ]
